name: pr-check

on:
  pull_request:
    branches:
      - main

permissions:
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: "27.0"
          elixir-version: "1.17.3"

      - name: Install dependencies
        run: mix deps.get

      - name: Test
        run: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} MIX_ENV=test mix do canopy.cover, canopy.github
